[programs.localnet]
groupchats = "BKYHC1UxAAvaeZagebJdQYumzVYuDfNhd6Apm3bhb6TA"
users = "MQoKr4WJAi9Yd59FjrvE3vWH2FKZk8PenjDjECTeGy3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
