[programs.localnet]
groupchats = "bJhvwTYCkQceANgeShZ4xaxUqEBPsV8e1NgRnLRymxs"
users = "7MaC2xrAmmFsuRBEkD6BEL3eJpXCmaikYhLM3eKBPhAH"

[programs.devnet]
groupchats = "bJhvwTYCkQceANgeShZ4xaxUqEBPsV8e1NgRnLRymxs"
users = "7MaC2xrAmmFsuRBEkD6BEL3eJpXCmaikYhLM3eKBPhAH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
